### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hidagans** [dante4rt/getgrass-bot#13]
root@yearigans:/home/yearigans/getgrass-bot# node index.js
/home/yearigans/getgrass-bot/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/yearigans/getgrass-bot/src/Bot.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by 0xAlvi** [comment]
update your nodejs to latest version

**Comment by dante4rt** [comment]
> root@yearigans:/home/yearigans/getgrass-bot# node index.js /home/yearigans/getgrass-bot/node_modules/axios/index.js:1 import axios from './lib/axios.js'; ^^^^^
> 
> SyntaxError: Unexpected identifier at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/home/yearigans/getgrass-bot/src/Bot.js:3:15) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

NodeJS version is not compatible.
